version: "3.6"
services:
  mongo:
    image: "mongo:4.0.7"
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=docker
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
  app:
    build:
      context: ./docker
    image: "laravelapp"
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html